FROM python:3.12-slim

WORKDIR /usr/src

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./ .

EXPOSE 80

# COPY entrypoint.sh /src/entrypoint.sh
# RUN chmod +x /src/entrypoint.sh

# CMD ["/src/entrypoint.sh"]

CMD ["fastapi", "run", "src/main.py", "--host","0.0.0.0","--port","80"]