FROM python:3.12-slim

WORKDIR /usr/src

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./ .

EXPOSE 80

CMD ["fastapi", "run", "src/main.py", "--host","0.0.0.0","--port","80"]